create table media_resource (
        id bigint generated by default as identity,
        entry_date timestamp not null,
        contentType varchar(255) not null,
        delete boolean not null,
        name varchar(255) not null,
        publicId varchar(255),
        size bigint not null,
        advert_id bigint,
        primary key (id)
);

alter table media_resource add constraint mediaResource_advert_fk foreign key (advert_id) references adverts;

