create table comments (
    id bigint generated by default as identity,
    entry_date timestamp not null,
    entry_user VARCHAR(100),

    date timestamp not null,
    ip_addr varchar(25),
    nick varchar(255),
    rate integer not null check (rate>=1 AND rate<=10),
    text CLOB NOT NULL not null,
    advert_id bigint,
    primary key (id)
);

alter table comments add constraint comments_adverts_fk foreign key (advert_id) references adverts;